apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: order
  namespace: order
  annotations:
    kubernetes.io/ingress.class: kong
username: order-consumer
credentials:
- order-jwt-credential
- order-acl-credential

