apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-plugin-inventory
  namespace: inventory
plugin: cors
config:
  origins: # add domain
  - "*"
  methods:
  - GET
  - POST
  headers:
  - Accept
  - Accept-Version
  - Content-Length
  - Content-MD5
  - Content-Type
  - Date
  - X-Auth-Token
  - Authorization
  exposed_headers:
  - X-Auth-Token
  credentials: true
  max_age: 3600
  preflight_continue: false
