# create group using acl then add credential name to credentials in consumer
apiVersion: v1
kind: Secret
metadata:
  name: admin-acl-credential
  namespace: inventory
  labels:
    konghq.com/credential: acl
stringData:
  group: admin-group # group for acl plugin allowed