apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
 name: admin
 namespace: inventory
 annotations:
   kubernetes.io/ingress.class: kong
username: admin
credentials:
- admin-jwt-credential
- admin-acl-credential
