admin:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

  ingress:
    enabled: true
    hostname: kong.admin.com
    path: /
    pathType: Prefix
    ingressClassName: kong
  env:
    password: kong_admin_password

ingressController:
  enabled: true
  env:
    publish_service: kong/kong-gateway-proxy #gateway proxy
    password: kong_admin_password

manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false

  ingress:
    enabled: true
    hostname: kong.manager.com
    path: /
    pathType: Prefix
    ingressClassName: kong

env:
   admin_gui_url: http://kong.manager.com
   admin_gui_api_url: http://kong.admin.com
